### PR TITLE
move config from qmd to separate toml

### LINKED ISSUE #304: Setting custom path for output files fails
Say  in `basic.toml` you add the line `basin = "myawesomefolder/basin.arrow"`, as indicated in [usage](https://deltares.github.io/Ribasim/core/usage.html). When running the Julia core on this TOML file, I now get this error:

```
ERROR: expect an AbstractDict or Ribasim.basin, got String
```

### PR DESCRIPTION
**Pull request by visr**
Fixes #304

The separate toml is included into the docs, so it looks the same as before. This way we can test this configuration to make sure it doesn't go out of date.

This checks in https://github.com/quarto-ext/include-code-files as suggested there.

### CODE REVIEW

File: docs/_extensions/quarto-ext/include-code-files/include-code-files.lua [hunk 1]
```diff
@@ -0,0 +1,62 @@
+--- include-code-files.lua – filter to include code from source files
```
Comment (Hofer-Julian) [inline docs/_extensions/quarto-ext/include-code-files/include-code-files.lua:1]: I assume there is no other way than vendoring at the moment?

**Review by evetion — APPROVED** [review]
Seems like a good improvement, although the lua includement is sad. Maybe merge this and make a tech-debt labeled issue to find a way to not have to include quarto extensions?

**Comment by visr** [comment]
The extension docs state:

> If you're using version control, you will want to check in this directory.

I guess we could avoid this, by adding `quarto add quarto-ext/include-code-files` to the dev docs and CI. But given that this was suggested and it is only a tiny bit of code and is simpler, I went for the suggested way.
